#!/usr/bin/env bash
# First-boot only: create isolated databases for gateway, server (pgvector), and keycloak.
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${POSTGRES_DB}" <<-EOSQL
CREATE USER ${GATEWAY_DB_USER} WITH PASSWORD '${GATEWAY_DB_PASSWORD}';
CREATE DATABASE ${GATEWAY_DB_NAME} OWNER ${GATEWAY_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${GATEWAY_DB_NAME} TO ${GATEWAY_DB_USER};

CREATE USER ${KB_DB_USER} WITH PASSWORD '${KB_DB_PASSWORD}';
CREATE DATABASE ${KB_DB_NAME} OWNER ${KB_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${KB_DB_NAME} TO ${KB_DB_USER};

CREATE USER ${KEYCLOAK_DB_USER} WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
CREATE DATABASE ${KEYCLOAK_DB_NAME} OWNER ${KEYCLOAK_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${KEYCLOAK_DB_NAME} TO ${KEYCLOAK_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" --dbname "${KB_DB_NAME}" <<-EOSQL
CREATE EXTENSION IF NOT EXISTS vector;
EOSQL
